// states
const states = [
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chandigarh',
    'Chhattisgarh',
    'Daman',
    'Delhi',
    'Goa',
    'Gujrat',
    'Haryana',
    'Himanchal Pradesh',
    'Jammu',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Ladakh',
    'Lakshadweep',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Port Blair',
    'Puducherry',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Srinagar',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttarakhand',
    'Uttar Pradesh',
    'West Bengal'
]

export default states;